---
- name: Verify
  hosts: all

  vars:
    miniconda_dir: "/opt/conda"
    install_miniconda: false

  roles:
    - role: base_miniconda

  tasks:

    - name: Update conda to latest version
      conda:
        executable: "{{ miniconda_dir }}/bin/conda"
        name: conda
        state: latest

    - name: Update conda again
      conda:
        executable: "{{ miniconda_dir }}/bin/conda"
        name: conda
        state: latest
      register: latest_test

    - name: Try to install a package that doesn't exist
      conda:
        executable: "{{ miniconda_dir }}/bin/conda"
        name: fakepackage13412351235
        state: present
      register: bad_install
      ignore_errors: true

    - name: Install numpy
      conda:
        executable: "{{ miniconda_dir }}/bin/conda"
        name: numpy
        state: present

    - name: Install numpy again
      conda:
        executable: "{{ miniconda_dir }}/bin/conda"
        name: numpy
        state: present
      register: present_test

    - name: Remove numpy
      conda:
        executable: "{{ miniconda_dir }}/bin/conda"
        name: numpy
        state: absent

    - name: Remove numpy again
      conda:
        executable: "{{ miniconda_dir }}/bin/conda"
        name: numpy
        state: absent
      register: absent_test

    - name: Verify idempotency of basic tasks
      assert:
        that:
          - not present_test.changed
          - not absent_test.changed
          - not latest_test.changed
          - bad_install is failed

    - name: Install multiple packages
      conda:
        executable: "{{ miniconda_dir }}/bin/conda"
        name:
          - pandas
          - sqlalchemy
        state: present

    - name: Install doxygen from conda-forge
      conda:
        executable: "{{ miniconda_dir }}/bin/conda"
        name: doxygen
        channels: conda-forge
